development:
  adapter: postgresql
  encoding: unicode
  database: wildrose2_development
  pool: 5
  username: kellywaters 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: wildrose2_test
  pool: 5
  username: kellywaters
  password: 